version: "3.7"

services:
 db:
  image: postgres:bullseye
  restart: always
  environment:
   POSTGRES_DB: postgres
   POSTGRES_USER: admin
   POSTGRES_PASSWORD: secret
   PGDATA: /var/lib/postgresql/data
  volumes:
   - db-data:/home/yuu/source/docker/docker-compose/postgres-compose/db-data
  ports:
   - "5432:5432"
 
 pgadmin:
  image: dpage/pgadmin4:5
  restart: always
  environment:
   PGADMIN_DEFAULT_EMAIL: admin@linuxhint.com
   PGADMIN_DEFAULT_PASSWORD: secret
   PGADMIN_LISTEN_PORT: 80
  ports:
   - "8080:80"
  volumes:
   - pgadmin-data:/home/yuu/source/docker/docker-compose/postgres-compose/pgadmin-data
  links:
   - "db:pgsql-server"
volumes:
 db-data: 
 pgadmin-data: 
